### PR TITLE
fix(dynamic apply): Add `path` key as candidate to list merging

### LINKED ISSUE #443: Using downwardApi without apiVersion leads to never-ending pod delete/recreate loop
metacontroller version 2.2.0

Using the downwardAPI in a pod spec seems to lead to a never ending cycle of destroying/recreating the pod. Example:

```
downwardAPI:
 items:
   - path: pod_name
     fieldRef:
       fieldPath: metadata.name
```

A workaround is to add apiVersion: v1 under the fieldRef from our side.

### PR DESCRIPTION
**Pull request by grzesuav**
fixes #443

Signed-off-by: grzesuav <grzesuav@gmail.com>

### CODE REVIEW

File: pkg/dynamic/apply/apply.go [hunk 1]
```diff
@@ -212,6 +212,7 @@ var knownMergeKeys = []string{
 	"name",
 	"uid",
 	"ip",
+	"path",
```
Comment (AmitKumarDas) [inline pkg/dynamic/apply/apply.go:215]: suggest: It will be great to add unit tests for this change

**Review by AmitKumarDas — APPROVED** [review]

File: pkg/dynamic/apply/apply.go (hunk 1 above)
Comment (grzesuav) [reply pkg/dynamic/apply/apply.go:215]: hmm generic mechanism is tested in `apply_test` (example with `containerPort`) - I can add in separate PR test for checking what are know Merge Keys to catch up regressions
